/// @file     Lib_Water_Voice.c
/// @date     2025/04/04
/// @author   Jaejin Ham
/// @brief    Voice Control file


#include "Global_Header.h"


#if (VOICE_IC_USE == USE)


/// @brief      무음 설정 상태에서 음성 출력이 되는 음성 체크
/// @details    무음 설정 상태에서 음성 출력이 되는 음성을 체크하여 출력 여부를 반환한다
/// @param      void
/// @return     return : 음성 출력 여부 - 0(음성 미출력), 1(음성 출력)
U8 IsLevel_Mute(U16 mu8Address)
{
    U8 mu8Return = 0;

    switch (mu8Address)
    {
        //case VOICE_1_SHUTOFF_WATER_FILTER_COVER:
        case VOICE_2_STOP_ICE_ICETANK_COVER:
        case VOICE_3_SHUTOFF_WATER_SIDE_COVER:
        //case VOICE_4_SHUTOFF_WATER_TOP_COVER:
        //case VOICE_5_SHUTOFF_WATER_FRONT_COVER:
        case VOICE_6_RESTART_ICE_COVER_OK:
        case VOICE_7_CALL_AS_COLD_WATER_ERROR:
        //case VOICE_8_CLEAN_DUST_FILTER_COLD_WATER_ERROR:
        case VOICE_9_CALL_AS_HOT_WATER_ERROR:
        case VOICE_10_CALL_AS_ICE_ERROR:
        case VOICE_11_CALL_AS_WATER_SUPPLY_ERROR:
        case VOICE_12_CALL_AS_WATER_LEAKAGE_ERROR:
        case VOICE_13_REPLACE_ONLY_FILTER_NO1_NO3:
        case VOICE_14_PRESS_RESET_BUTTON_AFTER_NEW_FILTER:
        case VOICE_15_REPLACE_ADD_FILTER_NO3_PLEASE:
        case VOICE_16_REPLACE_AFTER_CHECK_FILTER_NO1_NO3:
        case VOICE_17_REPLACE_ADD_FILTER_NO1_PLEASE:
        case VOICE_18_CLOSE_COVER_AFTER_FILTER_NO1_NO3:
        case VOICE_19_PRESS_YES_OR_NO_AFTER_FILTER_NO1_NO3:
        case VOICE_20_REPLACE_AFTER_CHECK_FILTER_NO1_NO3_V2:
        case VOICE_21_PRESS_YES_OR_NO_AFTER_FILTER_NO1_NO3_WELL:
        case VOICE_22_REPLACE_ONLY_FILTER_NO1_NO3_NOT_YET_NO2:
        case VOICE_23_START_FILTER_FLUSHING:
        case VOICE_24_FINISH_FILTER_FLUSHING:
        case VOICE_25_CHECK_FILTER_FLUSHING_MANUAL:
        case VOICE_26_REPLACE_FILTER_NO1_NO3:
        case VOICE_27_INFORM_ACTIVATED_FILTER_NO1_ADD_NO3:
        case VOICE_28_INFORM_ACTIVATED_FILTER_NO3_ADD_NO1:
        case VOICE_29_CLOSE_COVER_FOR_FILTER_FLUSHING:
        case VOICE_30_START_FILTER_FLUSHING_NO1_NO3:
        case VOICE_31_PRESS_RESET_BUTTON_AFTER_NEW_FILTER:
        case VOICE_32_PRESS_RESET_BUTTON_FILTER_NO1:
        case VOICE_33_PRESS_RESET_BUTTON_FILTER_NO3:
        case VOICE_34_REPLACE_ADD_FILTER_NO3:
        case VOICE_35_REPLACE_ADD_FILTER_NO1:
        case VOICE_36_CANCEL_RESET_FILTER_NO1:
        case VOICE_37_CANCEL_RESET_FILTER_NO2:
        case VOICE_38_CANCEL_RESET_FILTER_NO3:
        case VOICE_39_CANCEL_FILTER_FLUSHING:
        case VOICE_40_PRESS_RESET_BUTTON_NO1:
        case VOICE_41_PRESS_RESET_BUTTON_NO2:
        case VOICE_42_PRESS_RESET_BUTTON_NO3:
        case VOICE_43_REPLACE_ADD_FILTER_NO2_NO3_FOR_ALL:
        case VOICE_44_REPLACE_ADD_FILTER_NO1_NO3_FOR_ALL:
        case VOICE_45_REPLACE_ADD_FILTER_NO1_NO2_FOR_ALL:
        case VOICE_46_PRESS_YES_OR_NO_AFTER_ALL_FILTERS:
        case VOICE_47_CHECK_REPLACE_ALL_FILTERS:
        case VOICE_48_NOT_SELECTED_FILTER_FLUSHING:
        case VOICE_49_REPLACE_FILTER_ALL:
        case VOICE_50_INFORM_ACTIVATION_ADD_OTHER_FILTER:
        case VOICE_51_CLOSE_COVER_FOR_FILTER_FLUSHING_V2:
        case VOICE_52_PRESS_RESET_BUTTON_AFTER_REPLACE_FILTER:
        case VOICE_53_PRESS_RESET_BUTTON_DEACTIVATED:
        case VOICE_54_REPLACE_ADD_FILTER_NO3_FOR_ALL:
        case VOICE_55_REPLACE_ADD_FILTER_NO1_FOR_ALL:
        case VOICE_56_REPLACE_ADD_FILTER_NO2_FOR_ALL:
        case VOICE_57_PRESS_DISPENSE_BUTTON_AFTER_WATER_VALVE_OPEN:
        case VOICE_58_PRESS_YES_OR_NO_AFTER_FAUCET:
        case VOICE_59_PRESS_YES_OR_NO_AFTER_FILTER_FAUCET:
        ///case VOICE_60_WAIT_ICE_TANK_CLEANING:
        case VOICE_61_START_SMART_TESTING_MODE:
        case VOICE_62_FINISH_SMART_TESTING_MODE_NO_ERROR:
        case VOICE_63_FINISH_SMART_TESTING_MODE_WITH_ERROR:
        case VOICE_64_INFORM_BLE_MODE_ACTIVATED:
        case VOICE_65_INFORM_BLE_MODE_DEACTIVATED:
        case VOICE_66_INFORM_WIFI_MODE_ACTIVATED:
        case VOICE_67_INFORM_WIFI_MODE_DEACTIVATED:
        case VOICE_68_INFORM_WIFI_ON:
        case VOICE_69_INFORM_WIFI_OFF:
        case VOICE_70_PRESS_BUTTON_ACCORDING_TO_APP_GUIDE:
        case VOICE_71_INFORM_APP_PAIRING_SUCCESS:
        case VOICE_72_INFORM_APP_PAIRING_FAIL:
        case VOICE_73_INFORM_APP_DISCONNECTED:
        case VOICE_74_INFORM_WIFI_OFF:
        case VOICE_75_PRESS_INSTALL_BUTTON:
        //case VOICE_76_START_WIFI_AUTOMATIC_CONNECTION:
        //case VOICE_77_WAIT_WATER_PIPE_DRAIN:
        //case VOICE_78_DISCARD_FIRST_CUP:
        //case VOICE_79_WATCHOUT_HOT_WATER_CUP:
        //case VOICE_80_WATCHOUT_HOT_WATER_CONTINUOUS:
        //case VOICE_81_SETTING_MODE_CLEAN_CARE:
        //case VOICE_82_START_CLEAN_CARE_WATCHOUT_FAUCET:
        //case VOICE_83_PRESS_BUTTON_MANUAL_CLEAN_CARE:
        //case VOICE_84_START_CLEAN_CARE_WATCHOUT_HOT:
        //case VOICE_85_FINISH_CLEAN_CARE:
        //case VOICE_86_PRESS_BUTTON_MORE_SETTING_MODE:
        //case VOICE_87_SETTING_MODE:
        //case VOICE_88_CLOSE_FRONT_COVER:
        //case VOICE_89_CLOSE_SIDE_COVER:
        //case VOICE_90_CLOSE_TOP_COVER:
        //case VOICE_91_CLOSE_FILTER_COVER:
        //case VOICE_92_PRESS_BUTTON_HOT_LOCK_OFF:
        //case VOICE_93_PRESS_SETTING_MODE_HOT_LOCK_OFF:
        //case VOICE_94_PRESS_BUTTON_HOT_FUNCTION_ON:
        //case VOICE_95_CHECK_SETTING_HOT_FUNCTION:
        //case VOICE_96_CHECK_SETTING_COLD_FUNCTION:
        //case VOICE_97_DISPENSE_ICE_WHILE_PRESS:
        //case VOICE_98_INFORM_ICE_LOCK_ON:
        //case VOICE_99_PRESS_BUTTON_ICE_FUNCTION_ON:
        //case VOICE_100_SET_CLOCK_ECO_MODE:
        //case VOICE_101_NO_GUARANTEE_ICE_ECO_MODE:
        //case VOICE_102_PRESS_BUTTON_ALL_LOCK_OFF_A:
        //case VOICE_103_PRESS_SETTING_MODE_ALL_LOCK_OFF:
        //case VOICE_104_PRESS_BUTTON_ALL_LOCK_OFF_B:
        //case VOICE_105_WAIT_CLEAN_CARE:
        //case VOICE_106_SET_APP_AUTO_LOCK_OFF:
        //case VOICE_107_NO_GUARANTEE_LOW_WATER:
        //case VOICE_108_WAIT_LOW_WATER:
        //case VOICE_109_INFORM_NOT_ENOUGH_HOT:
        //case VOICE_110_INFORM_DISPENSE_NOT_ENOUGH_HOT:
        //case VOICE_111_INFORM_NOT_ENOUGH_COLD:
        //case VOICE_112_INFORM_HOT_LOCK_ON:
        //case VOICE_113_INFORM_HOT_LOCK_OFF:
        //case VOICE_114_SETTING_MODE_JOG_DAIL:
        //case VOICE_115_SETTING_HOT_TANK_CONTROL_MODE:
        //case VOICE_116_START_HEATING_HOT_TANK:
        //case VOICE_117_START_CONTROL_HOT_TANK:
        //case VOICE_118_INFORM_ENOUGH_HOT:
        //case VOICE_119_INFORM_TOO_HIGH_HOT:
        //case VOICE_120_SETTING_MODE_HOT_TANK:
        //case VOICE_121_INFORM_HOT_FUNCTION_ON:
        //case VOICE_122_INFORM_HOT_FUNCTION_OFF:
        //case VOICE_123_SETTING_MODE_COLD_TANK:
        //case VOICE_124_INFORM_COLD_FUNCTION_ON:
        //case VOICE_125_INFORM_COLD_FUNCTION_OFF:
        //case VOICE_126_SETTING_MODE_ALL_LOCK:
        //case VOICE_127_INFORM_ALL_LOCK_ON:
        //case VOICE_128_INFORM_ALL_LOCK_OFF:
        case VOICE_129_VOICE_MODE:
        case VOICE_130_MELODY_MODE:
        case VOICE_131_MUTE_MODE:
        case VOICE_132_SETTING_MODE_SOUND:
        //case VOICE_133_MODE_SET_VOICE:
        //case VOICE_134_MODE_SET_MELODY:
        //case VOICE_135_MODE_SET_MUTE:
        //case VOICE_136_MODE_SET_COLD_ON:
        //case VOICE_137_MODE_SET_COLD_OFF:
        //case VOICE_138_SETTING_MODE_CLEAN_CARE_TIME:
        //case VOICE_139_MODE_SET_CLEAN_CARE_TIME:
        //case VOICE_140_SETTING_MODE_DEFAULT_AMOUNT:
        //case VOICE_141_MODE_SET_DEFAULT_AMOUNT:
        //case VOICE_142_NOT_TIME_REPLACE_FILTER_YET:
        //case VOICE_143_CHECK_TIME_REPLACE_FILTER:
        //case VOICE_144_SETTING_MODE_CLOCK:
        //case VOICE_145_MODE_SET_CLOCK:
        //case VOICE_146_FINISH_SETTING:
        //case VOICE_147_INFORM_ICE_LOCK_ON:
        //case VOICE_148_INFORM_ICE_LOCK_OFF:
        //case VOICE_149_INFORM_ICE_FUNCTION_ON:
        //case VOICE_150_INFORM_ICE_FUNCTION_OFF:
        case VOICE_151_SPECIAL_FUNCTION:

        //case VOICE_192_MELODY_DISPENSE_CONTINUOUS:
        //case VOICE_193_MELODY_DISPENSE_START:
        //case VOICE_194_MELODY_DISPENSE_FINISH:
        case VOICE_195_MELODY_PLUG_IN:
        //case VOICE_196_MELODY_SELECT:
        //case VOICE_197_MELODY_WARNING:
        //case VOICE_198_MELODY_SET_ON:
        //case VOICE_199_MELODY_SET_OFF:

            mu8Return = TRUE;
            break;


        default :
            mu8Return = FALSE;
            break;
    }

    return  mu8Return;
}


/// @brief      멜로디 설정 상태에서 음성 출력이 되는 음성 체크
/// @details    멜로디 설정 상태에서 음성 출력이 되는 음성을 체크하여 출력 여부를 반환한다
/// @param      void
/// @return     return : 음성 출력 여부 - 0(음성 미출력), 1(음성 출력)
U8 IsLevel_Melody(U16 mu8Address)
{
    U8 mu8Return = 0;

    switch (mu8Address)
    {
        //case VOICE_1_SHUTOFF_WATER_FILTER_COVER:
        case VOICE_2_STOP_ICE_ICETANK_COVER:
        case VOICE_3_SHUTOFF_WATER_SIDE_COVER:
        //case VOICE_4_SHUTOFF_WATER_TOP_COVER:
        //case VOICE_5_SHUTOFF_WATER_FRONT_COVER:
        case VOICE_6_RESTART_ICE_COVER_OK:
        case VOICE_7_CALL_AS_COLD_WATER_ERROR:
        //case VOICE_8_CLEAN_DUST_FILTER_COLD_WATER_ERROR:
        case VOICE_9_CALL_AS_HOT_WATER_ERROR:
        case VOICE_10_CALL_AS_ICE_ERROR:
        case VOICE_11_CALL_AS_WATER_SUPPLY_ERROR:
        case VOICE_12_CALL_AS_WATER_LEAKAGE_ERROR:
        case VOICE_13_REPLACE_ONLY_FILTER_NO1_NO3:
        case VOICE_14_PRESS_RESET_BUTTON_AFTER_NEW_FILTER:
        case VOICE_15_REPLACE_ADD_FILTER_NO3_PLEASE:
        case VOICE_16_REPLACE_AFTER_CHECK_FILTER_NO1_NO3:
        case VOICE_17_REPLACE_ADD_FILTER_NO1_PLEASE:
        case VOICE_18_CLOSE_COVER_AFTER_FILTER_NO1_NO3:
        case VOICE_19_PRESS_YES_OR_NO_AFTER_FILTER_NO1_NO3:
        case VOICE_20_REPLACE_AFTER_CHECK_FILTER_NO1_NO3_V2:
        case VOICE_21_PRESS_YES_OR_NO_AFTER_FILTER_NO1_NO3_WELL:
        case VOICE_22_REPLACE_ONLY_FILTER_NO1_NO3_NOT_YET_NO2:
        case VOICE_23_START_FILTER_FLUSHING:
        case VOICE_24_FINISH_FILTER_FLUSHING:
        case VOICE_25_CHECK_FILTER_FLUSHING_MANUAL:
        case VOICE_26_REPLACE_FILTER_NO1_NO3:
        case VOICE_27_INFORM_ACTIVATED_FILTER_NO1_ADD_NO3:
        case VOICE_28_INFORM_ACTIVATED_FILTER_NO3_ADD_NO1:
        case VOICE_29_CLOSE_COVER_FOR_FILTER_FLUSHING:
        case VOICE_30_START_FILTER_FLUSHING_NO1_NO3:
        case VOICE_31_PRESS_RESET_BUTTON_AFTER_NEW_FILTER:
        case VOICE_32_PRESS_RESET_BUTTON_FILTER_NO1:
        case VOICE_33_PRESS_RESET_BUTTON_FILTER_NO3:
        case VOICE_34_REPLACE_ADD_FILTER_NO3:
        case VOICE_35_REPLACE_ADD_FILTER_NO1:
        case VOICE_36_CANCEL_RESET_FILTER_NO1:
        case VOICE_37_CANCEL_RESET_FILTER_NO2:
        case VOICE_38_CANCEL_RESET_FILTER_NO3:
        case VOICE_39_CANCEL_FILTER_FLUSHING:
        case VOICE_40_PRESS_RESET_BUTTON_NO1:
        case VOICE_41_PRESS_RESET_BUTTON_NO2:
        case VOICE_42_PRESS_RESET_BUTTON_NO3:
        case VOICE_43_REPLACE_ADD_FILTER_NO2_NO3_FOR_ALL:
        case VOICE_44_REPLACE_ADD_FILTER_NO1_NO3_FOR_ALL:
        case VOICE_45_REPLACE_ADD_FILTER_NO1_NO2_FOR_ALL:
        case VOICE_46_PRESS_YES_OR_NO_AFTER_ALL_FILTERS:
        case VOICE_47_CHECK_REPLACE_ALL_FILTERS:
        case VOICE_48_NOT_SELECTED_FILTER_FLUSHING:
        case VOICE_49_REPLACE_FILTER_ALL:
        case VOICE_50_INFORM_ACTIVATION_ADD_OTHER_FILTER:
        case VOICE_51_CLOSE_COVER_FOR_FILTER_FLUSHING_V2:
        case VOICE_52_PRESS_RESET_BUTTON_AFTER_REPLACE_FILTER:
        case VOICE_53_PRESS_RESET_BUTTON_DEACTIVATED:
        case VOICE_54_REPLACE_ADD_FILTER_NO3_FOR_ALL:
        case VOICE_55_REPLACE_ADD_FILTER_NO1_FOR_ALL:
        case VOICE_56_REPLACE_ADD_FILTER_NO2_FOR_ALL:
        case VOICE_57_PRESS_DISPENSE_BUTTON_AFTER_WATER_VALVE_OPEN:
        case VOICE_58_PRESS_YES_OR_NO_AFTER_FAUCET:
        case VOICE_59_PRESS_YES_OR_NO_AFTER_FILTER_FAUCET:
        case VOICE_60_WAIT_ICE_TANK_CLEANING:
        case VOICE_61_START_SMART_TESTING_MODE:
        case VOICE_62_FINISH_SMART_TESTING_MODE_NO_ERROR:
        case VOICE_63_FINISH_SMART_TESTING_MODE_WITH_ERROR:
        case VOICE_64_INFORM_BLE_MODE_ACTIVATED:
        case VOICE_65_INFORM_BLE_MODE_DEACTIVATED:
        case VOICE_66_INFORM_WIFI_MODE_ACTIVATED:
        case VOICE_67_INFORM_WIFI_MODE_DEACTIVATED:
        case VOICE_68_INFORM_WIFI_ON:
        case VOICE_69_INFORM_WIFI_OFF:
        case VOICE_70_PRESS_BUTTON_ACCORDING_TO_APP_GUIDE:
        case VOICE_71_INFORM_APP_PAIRING_SUCCESS:
        case VOICE_72_INFORM_APP_PAIRING_FAIL:
        case VOICE_73_INFORM_APP_DISCONNECTED:
        case VOICE_74_INFORM_WIFI_OFF:
        case VOICE_75_PRESS_INSTALL_BUTTON:
        //case VOICE_76_START_WIFI_AUTOMATIC_CONNECTION:
        //case VOICE_77_WAIT_WATER_PIPE_DRAIN:
        //case VOICE_78_DISCARD_FIRST_CUP:
        //case VOICE_79_WATCHOUT_HOT_WATER_CUP:
        //case VOICE_80_WATCHOUT_HOT_WATER_CONTINUOUS:
        //case VOICE_81_SETTING_MODE_CLEAN_CARE:
        //case VOICE_82_START_CLEAN_CARE_WATCHOUT_FAUCET:
        //case VOICE_83_PRESS_BUTTON_MANUAL_CLEAN_CARE:
        //case VOICE_84_START_CLEAN_CARE_WATCHOUT_HOT:
        //case VOICE_85_FINISH_CLEAN_CARE:
        //case VOICE_86_PRESS_BUTTON_MORE_SETTING_MODE:
        //case VOICE_87_SETTING_MODE:
        //case VOICE_88_CLOSE_FRONT_COVER:
        //case VOICE_89_CLOSE_SIDE_COVER:
        //case VOICE_90_CLOSE_TOP_COVER:
        //case VOICE_91_CLOSE_FILTER_COVER:
        //case VOICE_92_PRESS_BUTTON_HOT_LOCK_OFF:
        //case VOICE_93_PRESS_SETTING_MODE_HOT_LOCK_OFF:
        //case VOICE_94_PRESS_BUTTON_HOT_FUNCTION_ON:
        //case VOICE_95_CHECK_SETTING_HOT_FUNCTION:
        //case VOICE_96_CHECK_SETTING_COLD_FUNCTION:
        //case VOICE_97_DISPENSE_ICE_WHILE_PRESS:
        //case VOICE_98_INFORM_ICE_LOCK_ON:
        //case VOICE_99_PRESS_BUTTON_ICE_FUNCTION_ON:
        //case VOICE_100_SET_CLOCK_ECO_MODE:
        //case VOICE_101_NO_GUARANTEE_ICE_ECO_MODE:
        //case VOICE_102_PRESS_BUTTON_ALL_LOCK_OFF_A:
        //case VOICE_103_PRESS_SETTING_MODE_ALL_LOCK_OFF:
        //case VOICE_104_PRESS_BUTTON_ALL_LOCK_OFF_B:
        //case VOICE_105_WAIT_CLEAN_CARE:
        //case VOICE_106_SET_APP_AUTO_LOCK_OFF:
        //case VOICE_107_NO_GUARANTEE_LOW_WATER:
        //case VOICE_108_WAIT_LOW_WATER:
        //case VOICE_109_INFORM_NOT_ENOUGH_HOT:
        //case VOICE_110_INFORM_DISPENSE_NOT_ENOUGH_HOT:
        //case VOICE_111_INFORM_NOT_ENOUGH_COLD:
        //case VOICE_112_INFORM_HOT_LOCK_ON:
        //case VOICE_113_INFORM_HOT_LOCK_OFF:
        //case VOICE_114_SETTING_MODE_JOG_DAIL:
        //case VOICE_115_SETTING_HOT_TANK_CONTROL_MODE:
        //case VOICE_116_START_HEATING_HOT_TANK:
        //case VOICE_117_START_CONTROL_HOT_TANK:
        //case VOICE_118_INFORM_ENOUGH_HOT:
        //case VOICE_119_INFORM_TOO_HIGH_HOT:
        //case VOICE_120_SETTING_MODE_HOT_TANK:
        //case VOICE_121_INFORM_HOT_FUNCTION_ON:
        //case VOICE_122_INFORM_HOT_FUNCTION_OFF:
        //case VOICE_123_SETTING_MODE_COLD_TANK:
        //case VOICE_124_INFORM_COLD_FUNCTION_ON:
        //case VOICE_125_INFORM_COLD_FUNCTION_OFF:
        //case VOICE_126_SETTING_MODE_ALL_LOCK:
        //case VOICE_127_INFORM_ALL_LOCK_ON:
        //case VOICE_128_INFORM_ALL_LOCK_OFF:
        case VOICE_129_VOICE_MODE:
        case VOICE_130_MELODY_MODE:
        case VOICE_131_MUTE_MODE:
        case VOICE_132_SETTING_MODE_SOUND:
        //case VOICE_133_MODE_SET_VOICE:
        //case VOICE_134_MODE_SET_MELODY:
        //case VOICE_135_MODE_SET_MUTE:
        //case VOICE_136_MODE_SET_COLD_ON:
        //case VOICE_137_MODE_SET_COLD_OFF:
        //case VOICE_138_SETTING_MODE_CLEAN_CARE_TIME:
        //case VOICE_139_MODE_SET_CLEAN_CARE_TIME:
        //case VOICE_140_SETTING_MODE_DEFAULT_AMOUNT:
        //case VOICE_141_MODE_SET_DEFAULT_AMOUNT:
        //case VOICE_142_NOT_TIME_REPLACE_FILTER_YET:
        //case VOICE_143_CHECK_TIME_REPLACE_FILTER:
        //case VOICE_144_SETTING_MODE_CLOCK:
        //case VOICE_145_MODE_SET_CLOCK:
        //case VOICE_146_FINISH_SETTING:
        //case VOICE_147_INFORM_ICE_LOCK_ON:
        //case VOICE_148_INFORM_ICE_LOCK_OFF:
        //case VOICE_149_INFORM_ICE_FUNCTION_ON:
        //case VOICE_150_INFORM_ICE_FUNCTION_OFF:
        case VOICE_151_SPECIAL_FUNCTION:

        case VOICE_192_MELODY_DISPENSE_CONTINUOUS:
        case VOICE_193_MELODY_DISPENSE_START:
        case VOICE_194_MELODY_DISPENSE_FINISH:
        case VOICE_195_MELODY_PLUG_IN:
        case VOICE_196_MELODY_SELECT:
        case VOICE_197_MELODY_WARNING:
        case VOICE_198_MELODY_SET_ON:
        case VOICE_199_MELODY_SET_OFF:

            mu8Return = TRUE;
            break;

        default :
            mu8Return = FALSE;
    }

    return  mu8Return;
}


/// @brief      음성 설정 상태에서 음성 출력이 되는 음성 체크
/// @details    음성 설정 상태에서 음성 출력이 되는 음성을 체크하여 출력 여부를 반환한다
/// @param      void
/// @return     return : 음성 출력 여부 - 0(음성 미출력), 1(음성 출력)
U8 IsLevel_Voice(U16 mu8Address)
{
    U8 mu8Return = 0;

    switch (mu8Address)
    {
        case VOICE_1_SHUTOFF_WATER_FILTER_COVER:
        case VOICE_2_STOP_ICE_ICETANK_COVER:
        case VOICE_3_SHUTOFF_WATER_SIDE_COVER:
        case VOICE_4_SHUTOFF_WATER_TOP_COVER:
        case VOICE_5_SHUTOFF_WATER_FRONT_COVER:
        case VOICE_6_RESTART_ICE_COVER_OK:
        case VOICE_7_CALL_AS_COLD_WATER_ERROR:
        case VOICE_8_CLEAN_DUST_FILTER_COLD_WATER_ERROR:
        case VOICE_9_CALL_AS_HOT_WATER_ERROR:
        case VOICE_10_CALL_AS_ICE_ERROR:
        case VOICE_11_CALL_AS_WATER_SUPPLY_ERROR:
        case VOICE_12_CALL_AS_WATER_LEAKAGE_ERROR:
        case VOICE_13_REPLACE_ONLY_FILTER_NO1_NO3:
        case VOICE_14_PRESS_RESET_BUTTON_AFTER_NEW_FILTER:
        case VOICE_15_REPLACE_ADD_FILTER_NO3_PLEASE:
        case VOICE_16_REPLACE_AFTER_CHECK_FILTER_NO1_NO3:
        case VOICE_17_REPLACE_ADD_FILTER_NO1_PLEASE:
        case VOICE_18_CLOSE_COVER_AFTER_FILTER_NO1_NO3:
        case VOICE_19_PRESS_YES_OR_NO_AFTER_FILTER_NO1_NO3:
        case VOICE_20_REPLACE_AFTER_CHECK_FILTER_NO1_NO3_V2:
        case VOICE_21_PRESS_YES_OR_NO_AFTER_FILTER_NO1_NO3_WELL:
        case VOICE_22_REPLACE_ONLY_FILTER_NO1_NO3_NOT_YET_NO2:
        case VOICE_23_START_FILTER_FLUSHING:
        case VOICE_24_FINISH_FILTER_FLUSHING:
        case VOICE_25_CHECK_FILTER_FLUSHING_MANUAL:
        case VOICE_26_REPLACE_FILTER_NO1_NO3:
        case VOICE_27_INFORM_ACTIVATED_FILTER_NO1_ADD_NO3:
        case VOICE_28_INFORM_ACTIVATED_FILTER_NO3_ADD_NO1:
        case VOICE_29_CLOSE_COVER_FOR_FILTER_FLUSHING:
        case VOICE_30_START_FILTER_FLUSHING_NO1_NO3:
        case VOICE_31_PRESS_RESET_BUTTON_AFTER_NEW_FILTER:
        case VOICE_32_PRESS_RESET_BUTTON_FILTER_NO1:
        case VOICE_33_PRESS_RESET_BUTTON_FILTER_NO3:
        case VOICE_34_REPLACE_ADD_FILTER_NO3:
        case VOICE_35_REPLACE_ADD_FILTER_NO1:
        case VOICE_36_CANCEL_RESET_FILTER_NO1:
        case VOICE_37_CANCEL_RESET_FILTER_NO2:
        case VOICE_38_CANCEL_RESET_FILTER_NO3:
        case VOICE_39_CANCEL_FILTER_FLUSHING:
        case VOICE_40_PRESS_RESET_BUTTON_NO1:
        case VOICE_41_PRESS_RESET_BUTTON_NO2:
        case VOICE_42_PRESS_RESET_BUTTON_NO3:
        case VOICE_43_REPLACE_ADD_FILTER_NO2_NO3_FOR_ALL:
        case VOICE_44_REPLACE_ADD_FILTER_NO1_NO3_FOR_ALL:
        case VOICE_45_REPLACE_ADD_FILTER_NO1_NO2_FOR_ALL:
        case VOICE_46_PRESS_YES_OR_NO_AFTER_ALL_FILTERS:
        case VOICE_47_CHECK_REPLACE_ALL_FILTERS:
        case VOICE_48_NOT_SELECTED_FILTER_FLUSHING:
        case VOICE_49_REPLACE_FILTER_ALL:
        case VOICE_50_INFORM_ACTIVATION_ADD_OTHER_FILTER:
        case VOICE_51_CLOSE_COVER_FOR_FILTER_FLUSHING_V2:
        case VOICE_52_PRESS_RESET_BUTTON_AFTER_REPLACE_FILTER:
        case VOICE_53_PRESS_RESET_BUTTON_DEACTIVATED:
        case VOICE_54_REPLACE_ADD_FILTER_NO3_FOR_ALL:
        case VOICE_55_REPLACE_ADD_FILTER_NO1_FOR_ALL:
        case VOICE_56_REPLACE_ADD_FILTER_NO2_FOR_ALL:
        case VOICE_57_PRESS_DISPENSE_BUTTON_AFTER_WATER_VALVE_OPEN:
        case VOICE_58_PRESS_YES_OR_NO_AFTER_FAUCET:
        case VOICE_59_PRESS_YES_OR_NO_AFTER_FILTER_FAUCET:
        case VOICE_60_WAIT_ICE_TANK_CLEANING:
        case VOICE_61_START_SMART_TESTING_MODE:
        case VOICE_62_FINISH_SMART_TESTING_MODE_NO_ERROR:
        case VOICE_63_FINISH_SMART_TESTING_MODE_WITH_ERROR:
        case VOICE_64_INFORM_BLE_MODE_ACTIVATED:
        case VOICE_65_INFORM_BLE_MODE_DEACTIVATED:
        case VOICE_66_INFORM_WIFI_MODE_ACTIVATED:
        case VOICE_67_INFORM_WIFI_MODE_DEACTIVATED:
        case VOICE_68_INFORM_WIFI_ON:
        case VOICE_69_INFORM_WIFI_OFF:
        case VOICE_70_PRESS_BUTTON_ACCORDING_TO_APP_GUIDE:
        case VOICE_71_INFORM_APP_PAIRING_SUCCESS:
        case VOICE_72_INFORM_APP_PAIRING_FAIL:
        case VOICE_73_INFORM_APP_DISCONNECTED:
        case VOICE_74_INFORM_WIFI_OFF:
        case VOICE_75_PRESS_INSTALL_BUTTON:
        case VOICE_76_START_WIFI_AUTOMATIC_CONNECTION:
        case VOICE_77_WAIT_WATER_PIPE_DRAIN:
        case VOICE_78_DISCARD_FIRST_CUP:
        case VOICE_79_WATCHOUT_HOT_WATER_CUP:
        case VOICE_80_WATCHOUT_HOT_WATER_CONTINUOUS:
        case VOICE_81_SETTING_MODE_CLEAN_CARE:
        case VOICE_82_START_CLEAN_CARE_WATCHOUT_FAUCET:
        case VOICE_83_PRESS_BUTTON_MANUAL_CLEAN_CARE:
        case VOICE_84_START_CLEAN_CARE_WATCHOUT_HOT:
        case VOICE_85_FINISH_CLEAN_CARE:
        case VOICE_86_PRESS_BUTTON_MORE_SETTING_MODE:
        case VOICE_87_SETTING_MODE:
        case VOICE_88_CLOSE_FRONT_COVER:
        case VOICE_89_CLOSE_SIDE_COVER:
        case VOICE_90_CLOSE_TOP_COVER:
        case VOICE_91_CLOSE_FILTER_COVER:
        case VOICE_92_PRESS_BUTTON_HOT_LOCK_OFF:
        case VOICE_93_PRESS_SETTING_MODE_HOT_LOCK_OFF:
        case VOICE_94_PRESS_BUTTON_HOT_FUNCTION_ON:
        case VOICE_95_CHECK_SETTING_HOT_FUNCTION:
        case VOICE_96_CHECK_SETTING_COLD_FUNCTION:
        case VOICE_97_DISPENSE_ICE_WHILE_PRESS:
        case VOICE_98_INFORM_ICE_LOCK_ON:
        case VOICE_99_PRESS_BUTTON_ICE_FUNCTION_ON:
        case VOICE_100_SET_CLOCK_ECO_MODE:
        case VOICE_101_NO_GUARANTEE_ICE_ECO_MODE:
        case VOICE_102_PRESS_BUTTON_ALL_LOCK_OFF_A:
        case VOICE_103_PRESS_SETTING_MODE_ALL_LOCK_OFF:
        case VOICE_104_PRESS_BUTTON_ALL_LOCK_OFF_B:
        case VOICE_105_WAIT_CLEAN_CARE:
        case VOICE_106_SET_APP_AUTO_LOCK_OFF:
        case VOICE_107_NO_GUARANTEE_LOW_WATER:
        case VOICE_108_WAIT_LOW_WATER:
        case VOICE_109_INFORM_NOT_ENOUGH_HOT:
        case VOICE_110_INFORM_DISPENSE_NOT_ENOUGH_HOT:
        case VOICE_111_INFORM_NOT_ENOUGH_COLD:
        case VOICE_112_INFORM_HOT_LOCK_ON:
        case VOICE_113_INFORM_HOT_LOCK_OFF:
        case VOICE_114_SETTING_MODE_JOG_DAIL:
        case VOICE_115_SETTING_HOT_TANK_CONTROL_MODE:
        case VOICE_116_START_HEATING_HOT_TANK:
        case VOICE_117_START_CONTROL_HOT_TANK:
        case VOICE_118_INFORM_ENOUGH_HOT:
        case VOICE_119_INFORM_TOO_HIGH_HOT:
        case VOICE_120_SETTING_MODE_HOT_TANK:
        case VOICE_121_INFORM_HOT_FUNCTION_ON:
        case VOICE_122_INFORM_HOT_FUNCTION_OFF:
        case VOICE_123_SETTING_MODE_COLD_TANK:
        case VOICE_124_INFORM_COLD_FUNCTION_ON:
        case VOICE_125_INFORM_COLD_FUNCTION_OFF:
        case VOICE_126_SETTING_MODE_ALL_LOCK:
        case VOICE_127_INFORM_ALL_LOCK_ON:
        case VOICE_128_INFORM_ALL_LOCK_OFF:
        case VOICE_129_VOICE_MODE:
        case VOICE_130_MELODY_MODE:
        case VOICE_131_MUTE_MODE:
        case VOICE_132_SETTING_MODE_SOUND:
        case VOICE_133_MODE_SET_VOICE:
        case VOICE_134_MODE_SET_MELODY:
        case VOICE_135_MODE_SET_MUTE:
        case VOICE_136_MODE_SET_COLD_ON:
        case VOICE_137_MODE_SET_COLD_OFF:
        case VOICE_138_SETTING_MODE_CLEAN_CARE_TIME:
        case VOICE_139_MODE_SET_CLEAN_CARE_TIME:
        case VOICE_140_SETTING_MODE_DEFAULT_AMOUNT:
        case VOICE_141_MODE_SET_DEFAULT_AMOUNT:
        case VOICE_142_NOT_TIME_REPLACE_FILTER_YET:
        case VOICE_143_CHECK_TIME_REPLACE_FILTER:
        case VOICE_144_SETTING_MODE_CLOCK:
        case VOICE_145_MODE_SET_CLOCK:
        case VOICE_146_FINISH_SETTING:
        case VOICE_147_INFORM_ICE_LOCK_ON:
        case VOICE_148_INFORM_ICE_LOCK_OFF:
        case VOICE_149_INFORM_ICE_FUNCTION_ON:
        case VOICE_150_INFORM_ICE_FUNCTION_OFF:
        case VOICE_151_SPECIAL_FUNCTION:

        case VOICE_192_MELODY_DISPENSE_CONTINUOUS:
        case VOICE_193_MELODY_DISPENSE_START:
        case VOICE_194_MELODY_DISPENSE_FINISH:
        case VOICE_195_MELODY_PLUG_IN:
        case VOICE_196_MELODY_SELECT:
        case VOICE_197_MELODY_WARNING:
        case VOICE_198_MELODY_SET_ON:
        case VOICE_199_MELODY_SET_OFF:

            mu8Return = TRUE;
            break;

        default :
            mu8Return = FALSE;
            break;
    }

    return  mu8Return;
}


/// @brief      Critical 상태에서 반드시 음성 출력이 되는 음성 체크
/// @details    Critical 상태에서 음성 출력이 되는 음성을 체크하여 출력 여부를 반환한다
/// @param      void
/// @return     return : 음성 출력 여부 - 0(음성 미출력), 1(음성 출력)
U8 IsCriticalVoice(U16 mu8Address)
{
    U8 mu8Return = 0;

    switch (mu8Address)
    {
        //case VOICE_1_SHUTOFF_WATER_FILTER_COVER:
        //case VOICE_2_STOP_ICE_ICETANK_COVER:
        //case VOICE_3_SHUTOFF_WATER_SIDE_COVER:
        //case VOICE_4_SHUTOFF_WATER_TOP_COVER:
        //case VOICE_5_SHUTOFF_WATER_FRONT_COVER:
        //case VOICE_6_RESTART_ICE_COVER_OK:
        //case VOICE_7_CALL_AS_COLD_WATER_ERROR:
        //case VOICE_8_CLEAN_DUST_FILTER_COLD_WATER_ERROR:
        //case VOICE_9_CALL_AS_HOT_WATER_ERROR:
        //case VOICE_10_CALL_AS_ICE_ERROR:
        //case VOICE_11_CALL_AS_WATER_SUPPLY_ERROR:
        //case VOICE_12_CALL_AS_WATER_LEAKAGE_ERROR:
        //case VOICE_13_REPLACE_ONLY_FILTER_NO1_NO3:
        //case VOICE_14_PRESS_RESET_BUTTON_AFTER_NEW_FILTER:
        //case VOICE_15_REPLACE_ADD_FILTER_NO3_PLEASE:
        //case VOICE_16_REPLACE_AFTER_CHECK_FILTER_NO1_NO3:
        //case VOICE_17_REPLACE_ADD_FILTER_NO1_PLEASE:
        //case VOICE_18_CLOSE_COVER_AFTER_FILTER_NO1_NO3:
        //case VOICE_19_PRESS_YES_OR_NO_AFTER_FILTER_NO1_NO3:
        //case VOICE_20_REPLACE_AFTER_CHECK_FILTER_NO1_NO3_V2:
        //case VOICE_21_PRESS_YES_OR_NO_AFTER_FILTER_NO1_NO3_WELL:
        //case VOICE_22_REPLACE_ONLY_FILTER_NO1_NO3_NOT_YET_NO2:
        //case VOICE_23_START_FILTER_FLUSHING:
        //case VOICE_24_FINISH_FILTER_FLUSHING:
        //case VOICE_25_CHECK_FILTER_FLUSHING_MANUAL:
        //case VOICE_26_REPLACE_FILTER_NO1_NO3:
        //case VOICE_27_INFORM_ACTIVATED_FILTER_NO1_ADD_NO3:
        //case VOICE_28_INFORM_ACTIVATED_FILTER_NO3_ADD_NO1:
        //case VOICE_29_CLOSE_COVER_FOR_FILTER_FLUSHING:
        //case VOICE_30_START_FILTER_FLUSHING_NO1_NO3:
        //case VOICE_31_PRESS_RESET_BUTTON_AFTER_NEW_FILTER:
        //case VOICE_32_PRESS_RESET_BUTTON_FILTER_NO1:
        //case VOICE_33_PRESS_RESET_BUTTON_FILTER_NO3:
        //case VOICE_34_REPLACE_ADD_FILTER_NO3:
        //case VOICE_35_REPLACE_ADD_FILTER_NO1:
        //case VOICE_36_CANCEL_RESET_FILTER_NO1:
        //case VOICE_37_CANCEL_RESET_FILTER_NO2:
        //case VOICE_38_CANCEL_RESET_FILTER_NO3:
        //case VOICE_39_CANCEL_FILTER_FLUSHING:
        //case VOICE_40_PRESS_RESET_BUTTON_NO1:
        //case VOICE_41_PRESS_RESET_BUTTON_NO2:
        //case VOICE_42_PRESS_RESET_BUTTON_NO3:
        //case VOICE_43_REPLACE_ADD_FILTER_NO2_NO3_FOR_ALL:
        //case VOICE_44_REPLACE_ADD_FILTER_NO1_NO3_FOR_ALL:
        //case VOICE_45_REPLACE_ADD_FILTER_NO1_NO2_FOR_ALL:
        //case VOICE_46_PRESS_YES_OR_NO_AFTER_ALL_FILTERS:
        //case VOICE_47_CHECK_REPLACE_ALL_FILTERS:
        //case VOICE_48_NOT_SELECTED_FILTER_FLUSHING:
        //case VOICE_49_REPLACE_FILTER_ALL:
        //case VOICE_50_INFORM_ACTIVATION_ADD_OTHER_FILTER:
        //case VOICE_51_CLOSE_COVER_FOR_FILTER_FLUSHING_V2:
        //case VOICE_52_PRESS_RESET_BUTTON_AFTER_REPLACE_FILTER:
        //case VOICE_53_PRESS_RESET_BUTTON_DEACTIVATED:
        //case VOICE_54_REPLACE_ADD_FILTER_NO3_FOR_ALL:
        //case VOICE_55_REPLACE_ADD_FILTER_NO1_FOR_ALL:
        //case VOICE_56_REPLACE_ADD_FILTER_NO2_FOR_ALL:
        //case VOICE_57_PRESS_DISPENSE_BUTTON_AFTER_WATER_VALVE_OPEN:
        //case VOICE_58_PRESS_YES_OR_NO_AFTER_FAUCET:
        //case VOICE_59_PRESS_YES_OR_NO_AFTER_FILTER_FAUCET:
        //case VOICE_60_WAIT_ICE_TANK_CLEANING:
        //case VOICE_61_START_SMART_TESTING_MODE:
        //case VOICE_62_FINISH_SMART_TESTING_MODE_NO_ERROR:
        //case VOICE_63_FINISH_SMART_TESTING_MODE_WITH_ERROR:
        //case VOICE_64_INFORM_BLE_MODE_ACTIVATED:
        //case VOICE_65_INFORM_BLE_MODE_DEACTIVATED:
        //case VOICE_66_INFORM_WIFI_MODE_ACTIVATED:
        //case VOICE_67_INFORM_WIFI_MODE_DEACTIVATED:
        //case VOICE_68_INFORM_WIFI_ON:
        //case VOICE_69_INFORM_WIFI_OFF:
        //case VOICE_70_PRESS_BUTTON_ACCORDING_TO_APP_GUIDE:
        //case VOICE_71_INFORM_APP_PAIRING_SUCCESS:
        //case VOICE_72_INFORM_APP_PAIRING_FAIL:
        //case VOICE_73_INFORM_APP_DISCONNECTED:
        //case VOICE_74_INFORM_WIFI_OFF:
        //case VOICE_75_PRESS_INSTALL_BUTTON:
        //case VOICE_76_START_WIFI_AUTOMATIC_CONNECTION:
        //case VOICE_77_WAIT_WATER_PIPE_DRAIN:
        //case VOICE_78_DISCARD_FIRST_CUP:
        //case VOICE_79_WATCHOUT_HOT_WATER_CUP:
        //case VOICE_80_WATCHOUT_HOT_WATER_CONTINUOUS:
        //case VOICE_81_SETTING_MODE_CLEAN_CARE:
        //case VOICE_82_START_CLEAN_CARE_WATCHOUT_FAUCET:
        //case VOICE_83_PRESS_BUTTON_MANUAL_CLEAN_CARE:
        //case VOICE_84_START_CLEAN_CARE_WATCHOUT_HOT:
        //case VOICE_85_FINISH_CLEAN_CARE:
        //case VOICE_86_PRESS_BUTTON_MORE_SETTING_MODE:
        //case VOICE_87_SETTING_MODE:
        //case VOICE_88_CLOSE_FRONT_COVER:
        //case VOICE_89_CLOSE_SIDE_COVER:
        //case VOICE_90_CLOSE_TOP_COVER:
        //case VOICE_91_CLOSE_FILTER_COVER:
        //case VOICE_92_PRESS_BUTTON_HOT_LOCK_OFF:
        //case VOICE_93_PRESS_SETTING_MODE_HOT_LOCK_OFF:
        //case VOICE_94_PRESS_BUTTON_HOT_FUNCTION_ON:
        //case VOICE_95_CHECK_SETTING_HOT_FUNCTION:
        //case VOICE_96_CHECK_SETTING_COLD_FUNCTION:
        //case VOICE_97_DISPENSE_ICE_WHILE_PRESS:
        //case VOICE_98_INFORM_ICE_LOCK_ON:
        //case VOICE_99_PRESS_BUTTON_ICE_FUNCTION_ON:
        //case VOICE_100_SET_CLOCK_ECO_MODE:
        //case VOICE_101_NO_GUARANTEE_ICE_ECO_MODE:
        //case VOICE_102_PRESS_BUTTON_ALL_LOCK_OFF_A:
        //case VOICE_103_PRESS_SETTING_MODE_ALL_LOCK_OFF:
        //case VOICE_104_PRESS_BUTTON_ALL_LOCK_OFF_B:
        //case VOICE_105_WAIT_CLEAN_CARE:
        //case VOICE_106_SET_APP_AUTO_LOCK_OFF:
        //case VOICE_107_NO_GUARANTEE_LOW_WATER:
        //case VOICE_108_WAIT_LOW_WATER:
        //case VOICE_109_INFORM_NOT_ENOUGH_HOT:
        //case VOICE_110_INFORM_DISPENSE_NOT_ENOUGH_HOT:
        //case VOICE_111_INFORM_NOT_ENOUGH_COLD:
        //case VOICE_112_INFORM_HOT_LOCK_ON:
        //case VOICE_113_INFORM_HOT_LOCK_OFF:
        //case VOICE_114_SETTING_MODE_JOG_DAIL:
        //case VOICE_115_SETTING_HOT_TANK_CONTROL_MODE:
        //case VOICE_116_START_HEATING_HOT_TANK:
        //case VOICE_117_START_CONTROL_HOT_TANK:
        //case VOICE_118_INFORM_ENOUGH_HOT:
        //case VOICE_119_INFORM_TOO_HIGH_HOT:
        //case VOICE_120_SETTING_MODE_HOT_TANK:
        //case VOICE_121_INFORM_HOT_FUNCTION_ON:
        //case VOICE_122_INFORM_HOT_FUNCTION_OFF:
        //case VOICE_123_SETTING_MODE_COLD_TANK:
        //case VOICE_124_INFORM_COLD_FUNCTION_ON:
        //case VOICE_125_INFORM_COLD_FUNCTION_OFF:
        //case VOICE_126_SETTING_MODE_ALL_LOCK:
        //case VOICE_127_INFORM_ALL_LOCK_ON:
        //case VOICE_128_INFORM_ALL_LOCK_OFF:
        //case VOICE_129_VOICE_MODE:
        //case VOICE_130_MELODY_MODE:
        //case VOICE_131_MUTE_MODE:
        //case VOICE_132_SETTING_MODE_SOUND:
        //case VOICE_133_MODE_SET_VOICE:
        //case VOICE_134_MODE_SET_MELODY:
        //case VOICE_135_MODE_SET_MUTE:
        //case VOICE_136_MODE_SET_COLD_ON:
        //case VOICE_137_MODE_SET_COLD_OFF:
        //case VOICE_138_SETTING_MODE_CLEAN_CARE_TIME:
        //case VOICE_139_MODE_SET_CLEAN_CARE_TIME:
        //case VOICE_140_SETTING_MODE_DEFAULT_AMOUNT:
        //case VOICE_141_MODE_SET_DEFAULT_AMOUNT:
        //case VOICE_142_NOT_TIME_REPLACE_FILTER_YET:
        //case VOICE_143_CHECK_TIME_REPLACE_FILTER:
        //case VOICE_144_SETTING_MODE_CLOCK:
        //case VOICE_145_MODE_SET_CLOCK:
        //case VOICE_146_FINISH_SETTING:
        //case VOICE_147_INFORM_ICE_LOCK_ON:
        //case VOICE_148_INFORM_ICE_LOCK_OFF:
        //case VOICE_149_INFORM_ICE_FUNCTION_ON:
        //case VOICE_150_INFORM_ICE_FUNCTION_OFF:
        case VOICE_151_SPECIAL_FUNCTION :

        //case VOICE_192_MELODY_DISPENSE_CONTINUOUS:
        //case VOICE_193_MELODY_DISPENSE_START:
        //case VOICE_194_MELODY_DISPENSE_FINISH:
        case VOICE_195_MELODY_PLUG_IN:
        //case VOICE_196_MELODY_SELECT:
        //case VOICE_197_MELODY_WARNING:
        //case VOICE_198_MELODY_SET_ON:
        //case VOICE_199_MELODY_SET_OFF:

            mu8Return = TRUE;
            break;

        default :
            mu8Return = FALSE;
            break;
    }

    return  mu8Return;
}


#endif



