/// @file     Global_Header.h
/// @date     2025/02/17
/// @author   Jaejin Ham
/// @brief    Include Program header Files

#ifndef _GLOBAL_HEADER_H_
#define _GLOBAL_HEADER_H_

/*  아래의 코드 중 사용하지 않는 h파일 들은 모두 주석 처리하여 include 시키지 않고 미사용 처리한다  */

// Header files generated by code generator
// G23
// #include "r_smc_entry.h"
// G13
#include "r_cg_macrodriver.h"
#include "r_cg_adc.h"
#include "r_cg_cgc.h"
// #include "r_cg_intc.h"
#include "r_cg_port.h"
#include "r_cg_serial.h"
#include "r_cg_timer.h"
#include "r_cg_wdt.h"
#include "r_cg_userdefine.h"

#include "hw.h"

// First Include header
#include "Type_Define.h"
#include "User_Config.h"
#include "User_Define.h"
#include "Type_Convert.h"
#include "Water_Temp_Table.h"


// Header files for HW Driver
#include "Drv_AC_Motor.h"
#include "Drv_BLDC_Motor.h"
#include "Drv_BoostPump.h"
#include "Drv_Buzzer.h"
#include "Drv_DC_Fan.h"
#include "Drv_DC_Pump.h"
#include "Drv_Debug.h"
#include "Drv_EEPROM.h"
#include "Drv_EW_Module.h"
#include "Drv_Flowmeter.h"
#include "Drv_GeneralADC.h"
#include "Drv_HumidTempSensor.h"
#include "Drv_LeakSensor.h"
#include "Drv_ReedSW.h"
#include "Drv_RTC_EEPROM_ISL12026.h"
#include "Drv_SmallValve.h"
#include "Drv_Stepmotor.h"
#include "Drv_StirringMotor.h"
#include "Drv_TDS.h"
#include "Drv_UV.h"
#include "Drv_Valve.h"
#include "Drv_Voice_NXD1005.h"
#include "Drv_WaterLevelSensor.h"

/* 히팅 관련 */
#include "Drv_Heater.h"
#include "Drv_InstantaneousHeater.h"
/* 냉각 관련 */
#include "Drv_NormalComp.h"
#include "Drv_BLDC_Comp.h"
#include "Drv_TEM.h"
/* 얼음 관련 */
#include "Drv_AC_Motor_IceMaking.h"
#include "Drv_IceSwingBar.h"
#include "Drv_Input_IceTray.h"
#include "Drv_Motor_GasSwitch.h"
#include "Drv_Motor_IceDoor.h"
#include "Drv_Motor_IceTray.h"

// Header files for Operation
#include "Lib_ADConvert.h"
#include "Lib_Buzzer.h"
#include "Lib_EEPROM.h"
#include "Lib_Memento.h"
#include "Lib_OperationMode.h"
#include "Lib_RTC.h"
#include "Lib_TDS.h"
#include "Lib_TimeScheduler.h"
#include "Lib_Water_BoostPump.h"
#include "Lib_Water_Effluent.h"
#include "Lib_Water_ErrorCheck.h"
#include "Lib_Water_Fan.h"
#include "Lib_Water_LevelSensor.h"
#include "Lib_Water_PowerSave.h"
#include "Lib_Water_PTA_Mode.h"
#include "Lib_Water_Setup.h"
#include "Lib_Water_TankWaterInput.h"
#include "Lib_Water_TestMode.h"
#include "Lib_Water_UV_Sterilize.h"
#include "Lib_Water_Voice.h"
#include "Lib_Water_Debug.h"
/* 히팅 관련 */
#include "Lib_Water_Heater.h"
#include "Lib_Water_InstantaneousHeater.h"
/* 냉각 관련 */
#include "Lib_Water_Cool_BLDCComp.h"
#include "Lib_Water_Cool_NormalComp.h"
#include "Lib_Water_Cool_TEM.h"
/* 얼음 관련 */
#include "Lib_Water_IceMaking_ModeDecision.h"
#include "Lib_Water_IceMaking.h"

// Base header files
#include "Func_ADC.h"
#include "Func_External_Interrput.h"
#include "Func_Uart.h"
#include "Basic_Loop.h"


// Header files for Wifi
// #include "WIFI_control.h"


// Header files generated by user
#include "User_EEPROM.h"
#include "User_RTC.h"
#include "User_Main.h"

// User
#include "flushing.h"
#include "water_out.h"
#include "key.h"
#include "amount.h"
#include "hot_water.h"
#include "hot_water_out.h"
#include "heater.h"
#include "lever.h"

// library header files
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <math.h>

#define Sound(mu8Data)   {Set_BuzzerSelect(mu8Data);}

#endif
